services:
  nginx_gateway:
    image: nginx:latest
    container_name: nginx_gateway
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    networks:
      - hashtax_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - hashtax_network
    environment:
      - DOZZLE_LEVEL=info
      - DOZZLE_ADDR=:8888

networks:
  hashtax_network:
    external: true
