# =============================================================
#  hashimpact.io  +  api.hashimpact.io
# =============================================================

# ---------- Redirect HTTP to HTTPS ----------
server {
  listen 80;
  server_name hashimpact.io api.hashimpact.io;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

# ---------- hashimpact.io ----------
server {
  listen 443 ssl;
  http2 on;
  server_name hashimpact.io;

  ssl_certificate     /etc/letsencrypt/live/hashimpact.io/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/hashimpact.io/privkey.pem;

  include /etc/nginx/conf.d/ssl_params.conf;
  include /etc/nginx/conf.d/security_headers.conf;

  location / {
    set $upstream hashimpact_frontend:8081;
    proxy_pass         http://$upstream;
    include /etc/nginx/conf.d/proxy_params.conf;
  }
}

# ---------- api.hashimpact.io ----------
server {
  listen 443 ssl;
  http2 on;
  server_name api.hashimpact.io;

  ssl_certificate     /etc/letsencrypt/live/hashimpact.io/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/hashimpact.io/privkey.pem;

  include /etc/nginx/conf.d/ssl_params.conf;
  include /etc/nginx/conf.d/security_headers.conf;

  location / {
    set $upstream hashimpact_backend:8080;
    proxy_pass         http://$upstream;
    include /etc/nginx/conf.d/proxy_params.conf;
  }
}
