# =============================================================
#  tools.hashtax.io  +  tools-api.hashtax.io
# =============================================================

upstream hashtax_frontend {
    server hashtax_frontend:3000;
}

upstream hashtax_backend {
    server hashtax_backend:5000;
}

# ---------- tools.hashtax.io ----------
server {
  listen 80;
  server_name tools.hashtax.io;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    proxy_pass         http://hashtax_frontend;
    include /etc/nginx/conf.d/proxy_params.conf;
  }
}

# ---------- tools-api.hashtax.io ----------
server {
  listen 80;
  server_name tools-api.hashtax.io;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    proxy_pass         http://hashtax_backend;
    include /etc/nginx/conf.d/proxy_params.conf;
  }
}

